optimize deploy steps order

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,26 +17,6 @@ jobs:
       contents: read
 
     steps:
-      - name: Wait for biome check
-        uses: fountainhead/action-wait-for-check@v1.2.0
-        id: biome-check
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          checkName: biome-check
-
-      - name: Wait for typecheck
-        uses: fountainhead/action-wait-for-check@v1.2.0
-        id: typecheck
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          checkName: typecheck
-
-      - name: Exit if code quality checks failed
-        if: steps.biome-check.outputs.conclusion != 'success' || steps.typecheck.outputs.conclusion != 'success'
-        run: |
-          echo "Code quality checks failed"
-          exit 1
-
       - name: Checkout code
         uses: actions/checkout@v4
 
@@ -60,6 +40,27 @@ jobs:
       - name: Install Doppler CLI
         uses: dopplerhq/cli-action@v3
 
+
+      - name: Wait for biome check
+        uses: fountainhead/action-wait-for-check@v1.2.0
+        id: biome-check
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          checkName: biome-check
+
+      - name: Wait for typecheck
+        uses: fountainhead/action-wait-for-check@v1.2.0
+        id: typecheck
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          checkName: typecheck
+
+      - name: Exit if code quality checks failed
+        if: steps.biome-check.outputs.conclusion != 'success' || steps.typecheck.outputs.conclusion != 'success'
+        run: |
+          echo "Code quality checks failed"
+          exit 1
+
       - name: Deploy
         id: deploy
         env:
@@ -69,7 +70,7 @@ jobs:
           PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
           PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
           DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
-          SST_STAGE: ${{ github.ref == 'refs/heads/production' && 'production' || 'dev' }} 
+          SST_STAGE: ${{ github.ref == 'refs/heads/production' && 'production' || 'dev' }}
         run: |
           pnpm sst install
           pnpm sync_secrets
